### PR TITLE
The pull-request gate compiles every framework the packages ship

### PR DESCRIPTION
**Pull request by kirill-abblix**
Each test project targets `net10.0` alone, so the shards structurally cannot see anything that compiles there and refuses on `net8.0` or `net9.0` - a language feature of a newer version, a BCL type that arrived later. Such a refusal passed every check a pull request has and first appeared after the merge, in the job that packs the dev build, where it stops publishing without failing anything anyone is watching: consumers floating the prerelease range keep restoring the last good build and notice nothing.

A build job now compiles the solution in Release across all three frameworks, which is what the publish job does, and the existing aggregate check depends on it as well as on the shards.

Two decisions worth stating, because both look arbitrary until the reason is named:

- **The aggregate depends on the new job instead of the job standing beside it.** `Unit tests` is the name branch protection requires, so a separate check would only become required after a settings change, and the gap would stay open until somebody made it. Depending closes it on merge.
- **That name stays narrower than what it now covers.** Renaming a required check leaves every pull request waiting for a check that no longer appears, which is the failure the workflow's own comment already warns about.

### Verification

The instrument was proven capable of failing before being trusted: with the lock statement that broke develop planted back into `TokenSource`, the job's own build command reports `error CS9202` six times; with it removed, the same command is clean, `0 Warning(s) 0 Error(s)`. `actionlint` (with shellcheck on PATH) and the inline-secrets lint both pass. Timeouts come from the measurement - 1m35s for the build over a cold NuGet cache - rather than from a guess.

Checked: Inputs (no `${{ }}` in any `run:`), Permissions (workflow-root read, job-level read, aggregate `{}`), Pinning (all four `uses:` at full SHA with version comments, copied from the shard job), persist-credentials false, Timeouts (job and every step), harden-runner on a job that may build untrusted fork code. N/A: Secrets (none reachable), Cross-repo (single-repo workflow).

### CODE REVIEW

**Comment by kirill-abblix** [comment]
Checked against the security checklist: Inputs (no `${{ }}` in any `run:`; lint-no-inline-secrets clean), Permissions (workflow-root read, job-level `contents: read`, aggregate `{}`), Pinning (all four `uses:` verified against the action repos' own tag refs, not against the local comments), persist-credentials false, Timeouts (5/3 baseline, no override - the job's first run measured 3m00s end to end and 1m58s for the build), Concurrency (workflow-level cancel-in-progress already true), Failure semantics (no `|| true`), Cache and runner integrity (harden-runner audit on a job that may build fork-PR code; fork-PR cache writes are isolated by GitHub). N/A: Secrets (none reachable from this job), Cross-repo, Tag/release lifecycle, pip.

The gate was proven able to fail before being trusted: with the lock statement that broke develop planted into a temporary commit, `Build all target frameworks` and the required `Unit tests` check both went red while `shards / Tests (Abblix.Jwt.Vault.UnitTests)` stayed green on the same commit - which is exactly the gap this closes. The temporary commit was removed and the branch now carries only the two intended ones.
